
import { TipoLineaIntermediario } from './tipolineaintermediario.model';
import { UploadFilesIntermediario } from './uploadfilesintermediario.model';
import {User} from './user.model';
import {UserUpdate} from './userupdate.model';
export class Intermediario {
    saldocreditocobrado=0;
    fotoperfil: string = ' ';
    optionsearch:string;
    sigla:string;
    intermediariohistdocu:boolean;
    intermediariodocu: boolean;
    optiondocuhistintermediario:string;
    optiondocuintermediario:string;
    optioncreateuser:string;
    optionusersregister:string;
    optiontipoesquemacomisionregister:string;
    optionuser:string;
    optiontipoesquemacomision:string;
    optionintermediario:string;
    optionsearchintermediario:string;
    passwordcheck: string;
    role:string = 'intermediario';
    estado:string ;
    fechalimitereporte:Date;
    tipodocumento:string;
    pais:string = '';
    region:string = '';
    nit:string;
    documento:string  ;
    password:string  ;
    histpassword: string  ;
    nombre:string  ;
    descripcion:string = '';
    direccion:string = '';
    telefono:string;
    email:string;
    histemail:string ;
    ciudad:string = '';
    contacto:string = '';
    trabajocontacto:string = '';
    telefonocontacto:string = '';
    emailcontacto:string = '';
    personacorres:string = '';
    trabajopersonacorres:string = '';
    emailpersonacorres:string = '';
    telefonopersonacorres:string = '';
    coberturacreditomora=0;
    administracion=0;
    ivaadministracion=0;
    comisiontotal=0;
    cargues=0;
    saldototal=0;
    recuperacion;
    idrepresentante:string = ' ';
    rut:string = ' '; 
    camaracomercio:string = ' '; 
    certificacionbancaria:string = ' '; 
    contrato:string = ' ';  
    otrossi : string = ' ';;
    rol:string = '';
    maestro:string = '';
    permission:string = '';
    creadopor: string = '';
    creadoen: string = '';
    modificadopor: string = '';
    modificadoen: string = '';
    modificacioncausa:string= '';
    modificacioncausaedit:string= '';
    uploadfiles: UploadFilesIntermediario[] = [] = new Array<UploadFilesIntermediario>();
    uploadhistfiles: UploadFilesIntermediario[] = []= new Array<UploadFilesIntermediario>();
    lineasintermediario:TipoLineaIntermediario[] = [];
    users: User[] = [];
    userdoc: User = new User ();
    userupdate: UserUpdate = new UserUpdate();
    optioneditpassword:string = 'close';
    optionedituserintermediario:string = 'close';
    emailnew:string;
    emailcheck:string;
    emailold:string; 
    passwordnew:string; 
    passwordold:string;
    confirmacion:string; 
    intermediarios: Intermediario[] = []; 
    cantidadgarantias=0;
    intereses;
    gac;
    checknormal = false;
    checkdoble = false;
    validatesaldocreditocobrado;
 
}